---
version: "3.8"
services:
  git-server:
    build:
      context: "./"
      dockerfile: "Dockerfile.git-server"
    volumes:
      - "./git-repos:/repos"
    networks:
      default:
        aliases:
          - "git-server.local"
